### ISSUE TITLE
Eat own dog food.

### ISSUE THREAD

**Issue by lijunle** [59naga/babel-plugin-add-module-exports#10]
Unit test is important. However, it could be great to integrate this plugin back to itself - `export default` then `require` to test the exported stuffs.

If we are going to do it in test code, the test code needs to convert to ES6 syntax.

@59naga Any ideas?

**Comment by 59naga** [comment]
Behavior is now flat.
Tests Let's finish flat.

**Comment by lijunle** [comment]
What is the meaning of *flat* here?

**Comment by 59naga** [comment]
I've used *flat* meant *providing a single function*.
Currently, this plug-in, do the locally modifications to babel@6.
But the future, *flat* might be difficult for given the compatibility of babel@7.

(As you said) I think need to bit more consider a test case.

**Comment by lijunle** [comment]
Closing this by https://github.com/59naga/babel-plugin-add-module-exports/pull/33
