### ISSUE TITLE
Default should be exported as exports.default

### ISSUE THREAD

**Issue by lijunle** [59naga/babel-plugin-add-module-exports#12]
Are you [not](https://github.com/59naga/babel-plugin-add-module-exports/commit/36581888f9c60bd7bb0a2fe694f8d741d6caded5#diff-910eb6f57886ca16c136101fb1699231R60) exporting default to `exports.default`?

You are breaking this code:

```js
// export.js
export default 'entry';
```

```js
// import.js
import { default as entry } from './export';
```

**Comment by 59naga** [comment]
Yes. exports.default is `undefined`. __But is the behavior of babel@5__.

```bash
babel -V && babel --stage 0 es6.js
# 5.8.29 (babel-core 5.8.33)
# 'use strict';

# Object.defineProperty(exports, '__esModule', {
#   value: true
# });
# exports['default'] = 'entry';
# module.exports = exports['default'];
```

Your code works as long to compile with `babel-cli@6.1.18`. (__don't use__ this plugin for `babel-node`)

```bash
babel es6.js --presets es2015 --plugins add-module-exports > export.js
```

```js
import { default as entry } from './export';
```

This plugin was created to compile for [commonjs](https://github.com/babel/babel/issues/2212). (Original motivation in wrote at README.)

**Comment by lijunle** [comment]
Why you are say `undefined` in the behavior in babel@5?

Have you notice the last two line in your output?

```
babel -V && babel --stage 0 export.es6
# 5.8.29 (babel-core 5.8.33)
# 'use strict';

# Object.defineProperty(exports, '__esModule', {
#   value: true
# });
# exports['default'] = 'entry'; // <------------------------------ undefined?
# module.exports = exports['default'];
```

**Comment by lijunle** [comment]
This is the output of compilation of `import.js` file. **You are absolutely breaking the babel@5 behavior.**

```js
// import.js
import { default as d } from './export';
console.log(d);
```

```
lijunle:~/workspace $ ./node_modules/.bin/babel import.js 
'use strict';

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _export = require('./export');

var _export2 = _interopRequireDefault(_export);

console.log(_export2['default']); // <-------------------------- It is using default property
```

**Comment by 59naga** [comment]
It looks to be rewriting the test:

```bash
babel -V && babel src --out-dir lib5 --stage 0
# 5.8.29 (babel-core 5.8.33)
# src/export.js -> lib5/export.js
# src/import.js -> lib5/import.js

babel -V && babel src --out-dir lib6 --presets es2015 --plugins add-module-exports
# 6.1.18 (babel-core 6.1.21)
# src/export.js -> lib6/export.js
# src/import.js -> lib6/import.js
```

<img width="1680" alt="2015-11-17 00 30 43" src="https://cloud.githubusercontent.com/assets/1548478/11186038/23dd8696-8cc3-11e5-9b7c-7a2999d91900.png">

**Comment by lijunle** [comment]
I find that, you cannot manually test only with `import` declaration.

You need another statement to call the imported variable, use the following as an example:

```js
// import.js
import { default as d } from './export';
console.log(d);
```

**Comment by 59naga** [comment]
This test isn't required. `babel` will determine whether import at common or babel.
Rather than to ensure the results of the `import` declaration, should ensure the results of the `require` function?

**Comment by lijunle** [comment]
> This test isn't required. babel will determine whether import at common or babel.

Sadly, it won't.

**Comment by 59naga** [comment]
The current test has been carried out assignment against vm argument `module.exports`. Results are the `module.default` to `undefined`, it seemed to cause that is misleading as is broken compile the results.

```js
var vm = require('vm')
function createSandbox () {
  const exports = {}
  const sandbox = {
    exports,
    module: { exports },
    require: (path) => {
      delete require.cache[require.resolve(path)]
      return require(path)
    }
  }

  return sandbox
}


const sandbox = createSandbox()
vm.runInNewContext(`
'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});
exports['default'] = 'entry';
module.exports = exports['default'];
`, sandbox)

console.log(sandbox.module) // { exports: 'entry' }
console.log(sandbox.module.default) // undefined
```

**Comment by lijunle** [comment]
OK, I get the answer why you are passing the test cases. It is not the *magic* of babel, instead you are overriding the *magic* of babel. 

First, the `vm` logic is OK, its simulation for `require` call works fine.

The problem is `module.exports = exports['default'];` assignment.

Here is the output of using `add-module-exports` plugin.

```js
'use strict';

Object.defineProperty(exports, "__esModule", { // <--- define babel specified flag
  value: true
});
exports.default = 'this is the message';
module.exports = exports['default']; // <--- assign exports.default back to module.exports
```

Notice the `__esModule` flag, babel import behavior depends on this *magic* flag. Then, at the end of lines, you are assigning `exports.default` back to `module.exports`. After this assignment, `__esModule` flag is lost.

From babel's import function:

```js
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }
```

It retrieves module according to `__esModule` flag. If `true`, it is a babel module; it `false`, treat it as a legacy module.

Because your overriding lost the `__esModule` flag, babel treat the output as legacy module. As a legacy module, the output code is working.

However, I have no idea if `__esModule` is used in other places, if other magic functions depend on this flag. Please keep an eye on it.

**Comment by 59naga** [comment]
I understood that it is handled as default if __esModule is false.
And that, by the behavior of the future of babel, this is also that there is also a risk of causing unintended behavior.

**Comment by lijunle** [comment]
Yes, you are right. Anyway, I am OK with the *unintended behavior* of babel future version. We could just release 1.x to support babel@6 and 2.x for babel@7, etc.

BTW, do you know if node.js has a plan to support `import` declaration natively? If node.js handle this, this plugin can be retired.

**Comment by 59naga** [comment]
> do you know if node.js has a plan to support import declaration natively?

I know it now. That's a thing desirable.

**Comment by lijunle** [comment]
Er... I mean, does node.js have timetable to support import declaration?
