### ISSUE TITLE
Resolve npm version warning

### ISSUE THREAD

**Issue by lijunle** [59naga/babel-plugin-add-module-exports#15]
```
npm WARN engine babel-plugin-add-module-exports@0.1.1: wanted: {"npm":"^3.3.9"} (current: {"node":"0.10.35","npm":"3.3.6"})
```

Why do you want npm@^3.3.9 in package.json? I think you just want to use npm@3 in CI.

**Comment by 59naga** [comment]
Yes, this is unnecessary relic.
I previously was using the legacy `eslint-config-59naga` that depends on `npm dedupe`.

**Comment by lijunle** [comment]
Awesome, thanks!

**Comment by 59naga** [comment]
:beer:

**Comment by lijunle** [comment]
@59naga I am still seeing this warning from my build. Seem like you have not pushed it to npm.

**Comment by sorrycc** [comment]
:+1:
