### ISSUE TITLE
support amd formatter

### ISSUE THREAD

**Issue by zowers** [59naga/babel-plugin-add-module-exports#16]
can the plugin support babel-plugin-transform-es2015-modules-amd formatter?
the difference in amd module is that it will need to depend on `"module"` module

**Comment by 59naga** [comment]
Can't supported by this plugin.

Direct exports of amd will be the code, such as the following:

```js
define(function() {
  return 'foo';
});
```

But, it is not specified in the test of [babel-plugin-transform-es2015-modules-amd](https://github.com/babel/babel/tree/4c311ec2ab86544a23df866cb74feb25a859f0df/packages/babel-plugin-transform-es2015-modules-amd/test/fixtures/amd/).
