### ISSUE TITLE
Can I use this with `babel-plugin-rewire`

### ISSUE THREAD

**Issue by dtothefp** [59naga/babel-plugin-add-module-exports#19]
referenced here https://github.com/speedskater/babel-plugin-rewire/issues/80. Not sure which repo to put this issue on. 

This plugin works great except in combination with `rewire`. Is there a possible solution or are these two plugins incompatible?

```js
//some.js
export default {
  stuff: 'things'
}

//importer.js
import {stuff} from './some.js';

console.log(stuff); //undefined
```

```
{
  "presets": ["react", "es2015", "stage-0"],
  "plugins": ["add-module-exports", "rewire"]
}
```
or

```
{
  "presets": ["react", "es2015", "stage-0"],
  "plugins": ["rewire", "add-module-exports"]
}
```

**Comment by jdalton** [comment]
Is this still an issue?

**Comment by dtothefp** [comment]
@jdalton yes and it won't be addressed in rewire https://github.com/speedskater/babel-plugin-rewire/issues/80

**Comment by 59naga** [comment]
[tested using each of the latest version](https://gist.github.com/054e8a262fcb70fb15e19bf6f0660648.git), it was operating normally.
it will also add to this repository as the regression test.

**Comment by jdalton** [comment]
Nice! So that means the issues can be closed.

**Comment by 59naga** [comment]
ok, please report casually also. 👍
