### ISSUE TITLE
Should this be used in addition to transform-es2015-modules-commonjs, or instead of it? 

### ISSUE THREAD

**Issue by callumlocke** [59naga/babel-plugin-add-module-exports#22]
would be good to clarify this in the readme

**Comment by lijunle** [comment]
The `transform-es2015-modules-commonjs` is a part of `es2015` preset. This plugin co-work with the `es2015` preset - so, co-work with `...-commonjs`.

**Comment by hlomzik** [comment]
And also works with `transform-es2015-modules-umd` for me with such config (and only in such order, UMD *after* this plugin):
```json
{
"presets": ["es2015"],
"plugins": [
  "add-module-exports",
  "transform-es2015-modules-umd"
]
}
```

**Comment by lijunle** [comment]
@hlomzik great information, I update the README file (#23) to mention this.
