### ISSUE TITLE
Babel Core update broke this

### ISSUE THREAD

**Issue by jojobyte** [59naga/babel-plugin-add-module-exports#25]
My package.json was set to `"babel-core": "^6.3.26"`, when I installed a week or two ago it installed 6.4.5, when I cloned the repo on my laptop and ran `npm install` it installed 6.5.1, which caused this plugin to stop adding `module.exports = exports['default'];` for some reason.

Any ideas why this would stop working?

I've hard set my package.json to 6.4.5 for the time being.

**Comment by 59naga** [comment]
Hmm... Tell me the `your code` and `.babelrc` for reproduce?
Since all test work in my environment, we need more information.

```bash
git clone https://github.com/59naga/babel-plugin-add-module-exports.git ame
cd ame
node -v && npm -v && npm test
# v5.0.0
# 3.7.1
# ...
# 10 passing (604ms)
```

**Comment by jojobyte** [comment]
Ohhh, that is interesting. Admittedly, I did not have the plugin in .babelrc, it was being added in gulp in a webpack stream. Working on a library based on the Yo generator https://github.com/babel/generator-babel-boilerplate/blob/master/app/templates/gulpfile.babel.js

.babelrc
```json
{
  "presets": ["es2015"]
}
```

gulpfile.babel.js
```js
function build() {
	return gulp.src(path.join('src', config.entryFileName + '.js'))
		.pipe($.plumber())
		.pipe(webpackStream({
			output: {
				filename: exportFileName + '.js',
				library: config.mainVarName
			},
			module: {
				loaders: [
					{
						test: /\.js$/,
						exclude: /node_modules/,
						loader: 'babel-loader',
						query: {
							plugins: [
								'add-module-exports'
							]
						}
					}
				]
			},
			devtool: 'source-map'
		}))
		.pipe(gulp.dest(destinationFolder))
		.pipe($.filter(['*', '!**/*.js.map']))
		.pipe($.rename(exportFileName + '.min.js'))
		.pipe($.sourcemaps.init({ loadMaps: true }))
		.pipe($.uglify())
		.pipe($.sourcemaps.write('./'))
		.pipe(gulp.dest(destinationFolder));
}
```

Updating to the latest babel core (6.5.1) and changing .babelrc to whats below did fix it.
```json
{
  "presets": ["es2015"],
  "plugins": [
    "add-module-exports"
  ]
}
```

It was working with the previous code however. Odd. Guess I will mark this as closed.

**Comment by 59naga** [comment]
I see ... understood. will be helpful.
