### ISSUE TITLE
Strange behavior for looped dynamic require() statements

### ISSUE THREAD

**Issue by pkantsedalov** [59naga/babel-plugin-add-module-exports#26]
Hi everyone,

I have a directory with gulp tasks, each task's exported in the next way:
``` javascript
export default () => {
  return () => {

  };
}

```

Then I start to loop the dir stats in order to require these files dynamically: 
``` javascript

// loop starts

let taskFn = require(`${path}/${fileName}`);
taskFn(...);

// loop ends

```

But I have a problem - "default is not a function". So I did console.log(typeof taskFn) and found that the 1st file from directory is function, so works without .default, but all next - are objects with .default property. 

Seem it doesn't work with require at all:
``` javascript

let a = require('./build/gulp/tasks/a'); // typeof a === 'function'
let b = require('./build/gulp/tasks/b); // typeof b === 'object'

```
Babel v = 6.4.5

Please, help.

**Comment by lijunle** [comment]
What is the content of file a and file b? Besides, what happens if you change the order of the requires?

**Comment by pkantsedalov** [comment]
The content is the next one: 

``` javascript

export default() => {
  return () => { ... };
};

```

**Comment by lijunle** [comment]
1. I am not sure the space between `default` and `()` is critical. Please try.
2. Besides, what happens if you change the order of the requires?
3. Could you provide a mini-repo that repro this issue?

**Comment by pkantsedalov** [comment]
Very strange, but I've reinstalled the package and everything seems to be fine now.
Thank you a lot for your attention.
I think the question was in the global babel packages installed. On the machine which had this bug I have  babel-core, babel-node and babel-cli installed globally. But on another machine no babel packages are globally installed - and I don't have this strange bug.
