### ISSUE TITLE
Rename to babel-plugin-transform-add-module-exports

### ISSUE THREAD

**Issue by taion** [59naga/babel-plugin-add-module-exports#28]
Given that this is a transform, it seems like it'd be better to name it consistently with the bundled transforms.

**Comment by 59naga** [comment]
really? official of babel, don't use the prefix certainly "add". but, I don't know too much difference to me.
It is this would be a good change? @lijunle

**Comment by lijunle** [comment]
I think it will involve lots of changes. Many projects depend on this plugin now.

@taion besides the naming consistence, what other benefits from renaming?

**Comment by taion** [comment]
My thought is that if you use something like `npm deprecate`, people can see to move to the new package, so it shouldn't be too harmful. I can't think of any real benefits other than consistency, though.

**Comment by 59naga** [comment]
if it. consider the changes when turned to the `babel@7`.
