### ISSUE TITLE
How about rename to `babel-plugin-module-exports`?

### ISSUE THREAD

**Issue by lijunle** [59naga/babel-plugin-add-module-exports#3]
Just want to start a similar project, search on GitHub and find this. :heart: 

However, I think `babel-plugin-module-exports` is a better name - shorter, easier to remember. I find you use in [the test code](https://github.com/59naga/babel-plugin-add-module-exports/blob/master/test/index.js#L20), but not in the repo name and [package name](https://www.npmjs.com/package/babel-plugin-add-module-exports).

**Comment by 59naga** [comment]
Welcome.

For the name, since the official customary to start from the verb(e.g: `-transfrom-`), it is up to conforming to it.

**Comment by lijunle** [comment]
Hmm... Are you sure? https://www.npmjs.com/search?q=babel-plugin

**Comment by 59naga** [comment]
Oh, I had a look at the repository of [babel/babel/packages](https://github.com/babel/babel/tree/master/packages).

**Comment by lijunle** [comment]
OK, that is fine.
