### ISSUE TITLE
Breaks some end of file exports

### ISSUE THREAD

**Issue by lencioni** [59naga/babel-plugin-add-module-exports#30]
Thanks for your work on this plugin! I think I ran into an issue with this plugin when encountering code like:

```js
const foo = 1;
const BAR = 2;

export { foo as default, BAR };
```

I would expect there to be a default and a `BAR` named export. However, it seems as though there is only a default export in this case.

Here's a failing test case I wrote:

```js
{
  name: 'end of module export',
  code: 'const foo = 1;const BAR = 2;export { foo as default, BAR }',
  expected: {
    module: {
      default: 1,
      BAR: 2
    },
    exports: {
      default: 1,
      BAR: 2
    }
  }
},
```

**Comment by 59naga** [comment]
Even here confirmed, that is fixed. thanks @lencioni 👍
