### ISSUE TITLE
v0.1.3 is breaking changes?

### ISSUE THREAD

**Issue by iam4x** [59naga/babel-plugin-add-module-exports#31]
Hello,

We use this plugin in our babel preset (https://github.com/savemysmartphone/babel-preset-save), the minor update broke our builds.

I had to suffix the `require()` call to the plugin with `.default` see here: https://github.com/savemysmartphone/babel-preset-save/commit/3c9d67943efa41c9fe87809e25b4c2b0fd3680de

Is this normal behaviour? What happened? I can't find in the commit, this is just for personal knowledge. Thanks.

**Comment by 59naga** [comment]
hmm... this plug-in from the 0.1.3 no longer used the `module.exports`.
It has destroyed the compatibility of babel-presets.

**Comment by iam4x** [comment]
Alright, thank's. Would be great to publish a major for breaking changes like that 👍

**Comment by jquense** [comment]
this plugin needs to use itself :P

**Comment by lijunle** [comment]
It is on track actually :smily: #10

**Comment by 59naga** [comment]
this issue has been resolved in `v0.1.4`. thanks @iam4x 👍
