### ISSUE TITLE
Seems incompatible with ts-loader

### ISSUE THREAD

**Issue by viveleroi** [59naga/babel-plugin-add-module-exports#35]
I'm converting an app to typescript so I've added ts-loader to my chain. Due to the `export default` syntax I ran into the issue with babel your plugin solves. I've had success with this plugin with plain es2015 syntax but when ts-loader is involved it doesn't seem to work.

My .babelrc:

```
{
    "presets": ["es2015"],
    "plugins": [
        "add-module-exports",
        "lodash"
    ]
}
```

My webpack loader:

```
{
  test: /\.ts$/, loader: 'babel!ts-loader'
}
```

A simple class like:

    export default class Test {}

It works fine without ts-loader. 

Looking into this a little and I can see that with ts-loader, `hasExportDefault` is never true. I'm not yet sure why though.

With typescript, the following test module:

    export default class Test {}

... gets converted to this:

```
"use strict";
var Test = (function () {
    function Test() {
    }
    return Test;
}());
exports.__esModule = true;
exports["default"] = Test;
```

**Comment by 59naga** [comment]
if you want to use the `module.exports` in typescript, it seems to be the grammar of the following are available.

```js
// index.ts
export = class Test {}
```

```bash
tsc index.ts --module commonjs
```

becomes:

```js
module.exports = (function () {
    function Test() {
    }
    return Test;
})();
```

**Comment by viveleroi** [comment]
While it's not ideal to resort to an alternate syntax I've been trying to make it work, I've run this all in a dedicated test repo just to be sure nothing else in my larger project interferes.

While the combination of alternate `import`, `target=es5`, `module=commonjs`, and `export =` works correctly, it seems to break down when I try to use basic typescript features.

For example, if I try to use the imported library as a type, typescript errors with `error TS2304: Cannot find name 'B'.`:

```
import B = require('./b');

export = class Test {
	b: B;

	constructor() {
		console.log(new B());
	}
}
```

Also, libraries imported this unavailable to extend. For example in my live project I extend EventEmitter2 but now it errors with `Type 'typeof "./node_modules/eventemitter2/eventemitter2"' is not a constructor function type`.

Is it really not possible to adapt this plugin to account for the alternate syntax generated in the default typescript syntax? I feel like far more people would be using that.

**Comment by viveleroi** [comment]
Here's my test repo if it helps: https://github.com/helion3/tsc-test

**Comment by viveleroi** [comment]
Folks in the typescript gitter have steered me away from this import/export syntax, it clearly fails basic compilation though it is mentioned for some use-cases in their docs.

Looking at the output though, typescript is generating:

```
"use strict";
var Test = (function () {
    function Test() {
    }
    return Test;
}());
exports.__esModule = true;
exports["default"] = Test;
```

I don't have any idea why babel doesn't consider this `isExportDefaultDeclaration`, I assume it's just not officially the default.

I can make this work by adding the following - totally hacked together and possibly not the cleanest solution - to your plugin logic:

    // Account for exports['default']
    if (path.node.expression) {
       hasExportDefault = path.node.expression.left.property.value === 'default';
       return;
     }
 
If that's a change you're willing to accept I can PR it.
