### ISSUE TITLE
Follow the Babel@5 behavior

### ISSUE THREAD

**Issue by lijunle** [59naga/babel-plugin-add-module-exports#4]
The Babel 5 behavior could be:

1. If only default is exported, assign default to `module.exports` and `module.exports.default`.
2. If more than default is exported, keep nothing happens.

---

The current [implementation](https://github.com/59naga/babel-plugin-add-module-exports/blob/master/lib/index.js#L16) has some drawbacks:

- The default exported cannot be a function.
- The `exports` will override `exports.default` properties.

I could like to send a RP if you accept it.

**Comment by 59naga** [comment]
I'm waiting for the PR(but at out of the office).

Certainly, Than the current destructive implementation, it was in search of a better implementation.

**Comment by lijunle** [comment]
Could you mind me to refine the test code first? The current tests are fragile - they easily fails with future changes. I will work on it tomorrow.

**Comment by 59naga** [comment]
Fix to "assert the value of AST". seems good?

**Comment by lijunle** [comment]
I could rather require the output content and assert on the required object. That is how this plugin is used.

**Comment by 59naga** [comment]
In other words, should be assert the `Object of require('output code')`?

**Comment by lijunle** [comment]
Similarly, I am using [vm.runInNewContext](https://nodejs.org/api/vm.html#vm_vm_runinnewcontext_code_sandbox_options) to *require* the code.

**Comment by lijunle** [comment]
Besides, any good reason to keep [your own ESLint style config](https://www.npmjs.com/package/eslint-config-59naga)? Why not any existings, for example, [airbnb](https://github.com/airbnb/javascript), or [standard](https://github.com/feross/standard)?

It is a nightmare to run `npm run lint`. :angry:

**Comment by 59naga** [comment]
Change for this problem to:
* use eslint-config-standard
* use `eslint --fix`.

**Comment by 59naga** [comment]
Sorry, but I now go out.

Could not verified in detail how to use the vm(stumble to `undefined exports`), For now, was fix in form to assert object.

**Comment by lijunle** [comment]
Merge conflict... :cry: 

The diff: https://github.com/59naga/babel-plugin-add-module-exports/compare/master...lijunle:refine-tests

**Comment by lijunle** [comment]
@59naga Anyway, I am going to rebase to your top. Let me know if you moving ahead. We could better have a [gitter](https://gitter.im/) to discuss online. :blue_car:

**Comment by lijunle** [comment]
@59naga fail to rebase... Hope you are back.

I decided to work on my existing fork, please let me know you have time to chat.

**Comment by 59naga** [comment]
@lijunle Sorry, tied up today :sob:  But free on tomorrow :smile: I shall be ready the gitter by that time. :+1:

**Comment by lijunle** [comment]
@59naga could you like to review the spec of the deserved behavior in [this commit](https://github.com/lijunle/babel-plugin-add-module-exports/commit/8fe1ed98dbdad49f47c4fbc3e45b174778e898de)? The `expected.module` means the require should expose something *directly*, the `expected.exports` means the require expose *an object with* those properties.

**Comment by 59naga** [comment]
[line 20](https://github.com/lijunle/babel-plugin-add-module-exports/commit/8fe1ed98dbdad49f47c4fbc3e45b174778e898de#diff-910eb6f57886ca16c136101fb1699231R20)
If define a `default`, should be the `require` must always return the both of `default` and `exports`.
If the user isn't known the babel, to expected to the "module.exports" use "require".

```js
/// index.js
```

```js
// user.js
var entries = require('./index')
console.log(entries) // return {default:'default-entry',other: 'other-entry'} but should be 'default-entry'
```

**Comment by lijunle** [comment]
Hmmm... Is this current Babel 5 behavior?

**Comment by 59naga** [comment]
I will check.

**Comment by 59naga** [comment]
```js
const main = 'default-entry'

export default main
export const other = 'other-entry'
```

```bash
babel -V && babel index.js
# 5.8.34 (babel-core 5.8.34)
```

```js
'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});
var main = 'default-entry';

exports['default'] = main;
var other = 'other-entry';
exports.other = other;
```

**Comment by lijunle** [comment]
The `main` is not re-exposed as `module.exports`.

**Comment by 59naga** [comment]
Right. If you want to conform to the `babel@5`, in some cases to ignore module.exports.

**Comment by lijunle** [comment]
It depends on the road map of this package.

If it is an intermediate package for migrating to Babel@6, it could be better to follow Babel@5 bahavior.

If it wants to be a long-term package to convert Babel@6, go ahead with your definition. I am OK with that.

---

IMO, maybe maintain two versions is a better choice.

**Comment by 59naga** [comment]
Well... I take a _latter_ as a goal.

Can be export `default` and `others`, but, there is also a case where the user uses only `default`.

**Comment by lijunle** [comment]
I am OK with that, at least, that behavior is **compatible** with Babel@5. I will update the test spec soon. :smiley:

**Comment by lijunle** [comment]
I am updating the spec. However, I find some issue. If expose default to `module.exports` and bind others as `module.exports` properties.

This case will go into something wrong...

```js
const case = {
  name: 'not override default object with other export entries',
  code: 'export default { value: 1 }; export const value = 2',
  expected: {
    module: null,
    exports: {
      default: { value: 1 },
      value: 2
    }
  }
}
```

The `const value` will override `default.value`. Then unpredictable behavior could happens. :disappointed:

**Comment by 59naga** [comment]
```js
module.exports=Object.assign({},exports,exports.default);
```

Raise the priority of `exports.default`?

**Comment by lijunle** [comment]
Seems messy to me.

---

Think about such code:

```js
// index.js
function Cat() {
  this.name = 'cat'
}

Cat.prototype.say = function () {
    console.log(`${this.name} meow`)
}

/*
  myCat = Cat {
    name: 'cat',
    __proto__: {
      say: Cat.prototype.say
    }
  }
 */
const myCat = new Cat()
console.log(myCat.say()) // cat meow

export default myCat

export function say() {
  console.log('something')
}
```

After your mix-in (`Object.assign`), the `module.exports` comes into:

```js
module.exports = {
  name: 'cat',
  __proto__: { // I am not sure if this special __proto__ property will be mixed in
    say: Cat.prototype.say
  },
  say: () => console.log('something') // the explicit export one
}
```

In your `require` code, invoke `cat.say` method will go into the `something` one.

```js
// require.js
import cat from './index'

console.log(cat.say()) // something, expecting cat meow
```

**Comment by 59naga** [comment]
This, it seems to be the most safe behavior of `babel@5` ...

**Comment by lijunle** [comment]
Sure, let us follow the Babel@5 behavior first. :santa:

**Comment by 59naga** [comment]
The latter is on hold, And the former was implement for now.
I think want to close the issue.

**Comment by lijunle** [comment]
I think your implementation a better, however my test is better. :)

**Comment by 59naga** [comment]
Ok, I trying adjust test with your PR tests.

**Comment by 59naga** [comment]
Hmm ... Do not write a statically `[spec.js](https://github.com/lijunle/babel-plugin-add-module-exports/blob/f27bfe986eb9aaa8adb9e32b117ec71bb4c328f2/test/spec.js)`?

When dynamically generating a `spec`, not display the line number when an exception occurs, it is difficult to fix.

**Comment by lijunle** [comment]
That is data driven. When more data comes in, modify the spec then update.

**Comment by 59naga** [comment]
Thanks @lijunle ! if there is a need to verify the many more test, it looks in effective way. :beer:
