### ISSUE TITLE
Incompatibility issue

### ISSUE THREAD

**Issue by cwagner22** [59naga/babel-plugin-add-module-exports#43]
I've lost 4 days of my life debugging an issue until I realized that it was because I was using a library with this line 
`require('./browser').default;` from [Realm](https://github.com/realm/realm-js/blob/v1.2.0/lib/index.js#L87)

The result was undefined because of this plugin, so I had to stop using it. I wish it was still possible to use `.default`, to avoid incompatibilities with other libraries like Realm.

**Comment by DvdGiessen** [comment]
Just ran across the same issue. I have previously published a small library without using this plugin, and I now consider starting to use it. However, I don't want to break compatibility for users currently using `require().default`.

We could add an option to this plugin to make it add the default property as an alias, maintaining backward compatibility for code already having used the named default export. By making it opt-in, this functionality would not break anything for current users of this plugin, but would allow authors such as myself to support code using both a plain `require()` and `require().default`.

Configuration could look like this:
```json
["add-module-exports", {
   "addDefaultProperty": true
}]
```
Opting in by toggling that option to true would cause a second line of code to be added:
```diff
      module.exports = exports['default'];
>     module.exports.default = exports['default']
```

@59naga I'd be happy to open a pull request for such a change if this sounds like a valuable addition.
