### ISSUE TITLE
npmjs package page doesn't show readme

### ISSUE THREAD

**Issue by josephfrazier** [59naga/babel-plugin-add-module-exports#44]
At https://www.npmjs.com/package/babel-plugin-add-module-exports, it says there is no readme:

<img width="539" alt="screen shot 2017-04-30 at 5 50 42 pm" src="https://cloud.githubusercontent.com/assets/6473925/25568291/95041c0c-2dcd-11e7-84e6-c6529b551d85.png">

This is because the published package does not include README.md:

```bash
$ tar tvf $(npm pack babel-plugin-add-module-exports)
-rw-rw-r--  0 1000   1000     2433 May 12  2016 package/package.json
-rw-rw-r--  0 1000   1000     2133 May 12  2016 package/changelog.js
-rw-rw-r--  0 1000   1000    13185 May 12  2016 package/CHANGELOG.md
-rw-rw-r--  0 1000   1000     1293 May 12  2016 package/lib/index.js
-rw-rw-r--  0 1000   1000     2299 May 12  2016 package/lib/index.js.map
$
```

According to https://github.com/npm/registry/issues/120#issuecomment-276157329, old versions of npm didn't include README.md. If you upgrade your npm version, and publish a patch release of this module, the readme should appear on npmjs.com.

---

(issue markdown adapted from https://github.com/domenic/opener/issues/24)

**Comment by gluons** [comment]
@59naga Could you push the **README** file to **NPM**?

**Comment by alundiak** [comment]
I see readme, so this issue can be closed.

**Comment by gluons** [comment]
Yes. `v1.0.0` has been released. Readme is now available.

@59naga You can close this now.
