### ISSUE TITLE
Any plans to add babel 7 support?

### ISSUE THREAD

**Issue by eudisd** [59naga/babel-plugin-add-module-exports#51]
ERROR in ./src/buttons/Button/Button.js
Getting this error with babel 7:
```bash
Module build failed: Error: This API has been removed. If you're looking for this functionality in Babel 7, you should import the '@babel/helper-module-imports' module and use the functions exposed  from that module, such as 'addNamed' or 'addDefault'.
    at File.addImport (/Users/user/github/web/node_modules/@babel/core/lib/transformation/file/file.js:112:11)
    at /Users/user/github/web/node_modules/babel-plugin-react-transform/lib/index.js:259:46```

**Comment by lijunle** [comment]
I am not sure how @59naga think about this. My personal suggestion is **not** to support future babel versions.

This plugin is making the non-ECMAScript standard code viable in +1 babel version. However, the author still needs to convert the code to follow the ES module standard.

It is always hard time to make breaking change but another major version bump up seems good chance to me.

Ideas?

**Comment by DvdGiessen** [comment]
I agree that non-standard behaviour is made possible by this plugin and code that relies on that (see https://github.com/babel/babel/issues/2212#issuecomment-131110500 as an example) should be considered bad form. Authors should indeed be forced to convert such code (that is, if they wish to follow along and use newer Babel versions).

However, I also see a use case for code that is using standard exports and already works correctly without this plugin. In my case. I'm not using the plugin right now, but would consider it to be able to offer a cleaner API for users using ES5 syntax imports for my library (which is pretty much done functionality-wise and will not have to offer additional exports in the future).

@59naga What is your take on this? Given recent surge in development I wonder whether you plan to support upcoming Babel versions, or whether this will still be limited to Babel 6?

**Comment by 59naga** [comment]
Is no plan to deal with un-standard export syntax. we should develop an other plugin for this.
I'll continue maintenance considering `babel@7`, and don't think any more features should be added to this plugin.
