### ISSUE TITLE
Not work with vue-loader

### ISSUE THREAD

**Issue by blacider** [59naga/babel-plugin-add-module-exports#55]
module test.vue:

`<script>`
`export default {`
   ` n: 1    `
`}`
`</script>
`

index.js:
`
let x = require('./test.vue');`
`
import test from "test.vue";`
`
console.log(x, test);
`

output: 
![image](https://user-images.githubusercontent.com/9719148/42040793-0aeaa668-7b23-11e8-8b53-f5e15d14f0c7.png)

Variable `n` has only `get()` and no 'set()'. why?

`get()` will disappear when I remove The plugin.
![image](https://user-images.githubusercontent.com/9719148/42041197-f9ae93e0-7b23-11e8-8dfe-8269843e1cee.png)

Could you tell me what I should do? Thanks

**Comment by 59naga** [comment]
There is a problem with the code generated by this plugin, is there an environment that can be small reproduced?

**Comment by blacider** [comment]
Thank you very much for your reply. The [environment](https://github.com/blacider/webpack-demo-common) is ready.

**Comment by 59naga** [comment]
There is a nothing problem with the code generated by this plugin. If you don't use this plugin and use only `import` syntax without `require`, will not you solve the problem?

If you want to get similar results with `import` and `require`, please use [`addDefaultProperty` option](https://github.com/59naga/babel-plugin-add-module-exports#v030).
