### ISSUE TITLE
[bug] the init maybe null, pls try add some error handler here

### ISSUE THREAD

**Issue by dingziqi** [59naga/babel-plugin-add-module-exports#60]
![image](https://user-images.githubusercontent.com/16345383/42623712-26facbac-85f6-11e8-9584-66e3a88393fa.png)

**Comment by 59naga** [comment]
What kind of syntax did you use? I think the same problem as https://github.com/59naga/babel-plugin-add-module-exports/issues/58

**Comment by dingziqi** [comment]
Decorator or static，and this is only happend with other babel plugin，I didn't know which caused it.
