### ISSUE TITLE
babel-plugin-add-module-exports => @babel/plugin-add-module-exports ?

### ISSUE THREAD

**Issue by alundiak** [59naga/babel-plugin-add-module-exports#69]
Any plans? 
Does it make sense to use this plugin at all with Babel 7?

**Comment by wolfy1339** [comment]
This plugin is compatible with Babel 7 as of v1.0.0
As for the `@babel/plugin-add-module-exports` package name in the title, that won't happen unless this package becomes part of Babel's first-party plugins

**Comment by alundiak** [comment]
Thanks for the answer. Closing.
