### ISSUE TITLE
Does not support combination of named and default exports

### ISSUE THREAD

**Issue by stevenvachon** [59naga/babel-plugin-add-module-exports#81]
```js
export const CONSTANT_NAME = "value";
export default class ClassName{}
```
(which allows for doing):
```js
import ClassName, {CONSTANT_NAME} from "./module";
```

The transpiled file does not contain `module.exports = exports['default']`.

**Comment by ljharb** [comment]
That's not what this transform is supposed to cover; only modules with nothing but a default export are eligible.

If you want that semantic, you need to add properties to your default export, not use named export syntax.

**Comment by stevenvachon** [comment]
@ljharb but I want *everything* polyfilled.

**Comment by ljharb** [comment]
This is syntax, so polyfilling doesn’t even apply - the point of this transform is so your ES Modules that have only a default export, work properly with require.

If you have any named exports, you don’t need this transform for it to work how you want.

**Comment by stevenvachon** [comment]
Can the point of this transform not be adjusted?

**Comment by ljharb** [comment]
That'd be useless and silly, since what you want *is what babel does by default already*.

**Comment by stevenvachon** [comment]
But it isn't. I do also add the properties to the default export with a `// for CommonJS` comment for clarity.

What Babel does by default requires the ugly `.default`.

**Comment by stevenvachon** [comment]
This transform could benefit from a `ignoreNamedExports` option for this specific situation when there're both named and default exports.

**Comment by ljharb** [comment]
ah - so what you want is for a babel transform to silently and observably mutate the default export - which would fail at runtime if it was, for example, frozen?

That sounds like a terrible idea, and definitely something for a different transform.

CJS only *has* one (default) export. It is wildly incorrect to attempt to transform "more than one export" into "one export".

**Comment by stevenvachon** [comment]
```js
export const CONSTANT_NAME = "value";
export default class ClassName{}

Object.assign(ClassName, {CONSTANT_NAME}); // for CommonJS
```
->
```js
exports.CONSTANT_NAME = "value";
exports["default"] = ClassName;
module.exports = exports["default"];

Object.assign(ClassName, {CONSTANT_NAME}); // for CommonJS
```

**Comment by stevenvachon** [comment]
Ugh, that breaks ESM
